### PR TITLE
fix(module): exclude test files from Nuxt plugin registration

### LINKED ISSUE #1203: No test suite found inside of "plugins" folder
### Environment

Working directory: /home/olada/nuxt-starter-ebey3puz                                                                                                                  nuxi  00:02:27
Nuxt project info:                                                                                                                                                    nuxi  00:02:27

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.16.1
- CLI Version:      3.23.1
- Nitro Version:    2.11.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, pages, modules
- Runtime Modules:  @nuxt/test-utils/module@3.17.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/olada/nuxt-starter-ebey3puz

Run `pnpm test` (automatically run when opening the reproduction)

### Describe the bug

I have attempted to write a test for a plugin I have written.

I was surprised to find that vitest shows an error message that no test suite can be found

```
❯ plugins/customFetch.nuxt.spec.ts (0 test)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  plugins/customFetch.nuxt.spec.ts [ plugins/customFetch.nuxt.spec.ts ]
Error: No test suite found in file /home/olada/nuxt-starter-ebey3puz/plugins/customFetch.nuxt.spec.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯


 Test Files  1 failed (1)
      Tests  no tests
   Start at  00:01:38
   Duration  506ms

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.

 ELIFECYCLE  Test failed. See above for more details.
```

When renaming the folder "plugins" to e.g. "pluginss" or when moving the file /plugins/customFetch.spec.ts to /plugins/__tests__/customFetch.spec.ts the tests are correctly picked up.

It seems that nuxt somehow interferes with the test strategy of placing the tests into the very same directory as the "live code".

As a side note: Nuxt detects the spec file as a plugin and renders a warning that no default export was found inside of the .spec. file. 
```
[warn] [nuxt] Plugin `/home/olada/nuxt-starter-ebey3puz/plugins/customFetch.nuxt.spec.ts` has no default export and will be ignored at build time. Add `export default defineNuxtPlugin(() => {})` to your plugin.
```

Maybe the fact that Nuxt interpretes spec-files as a real plugin is related to the whole "no test suite found" issue?

### Additional context

_No response_

### Logs

```shell-script
RERUN  plugins/customFetch.nuxt.spec.ts x1 

[warn] [nuxt] Plugin `/home/olada/nuxt-starter-ebey3puz/plugins/customFetch.nuxt.spec.ts` has no default export and will be ignored at build time. Add `export default defineNuxtPlugin(() => {})` to your plugin.
 ❯ plugins/customFetch.nuxt.spec.ts (0 test)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  plugins/customFetch.nuxt.spec.ts [ plugins/customFetch.nuxt.spec.ts ]
Error: No test suite found in file /home/olada/nuxt-starter-ebey3puz/plugins/customFetch.nuxt.spec.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯


 Test Files  1 failed (1)
      Tests  no tests
   Start at  00:01:38
   Duration  506ms

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.

 ELIFECYCLE  Test failed. See above for more details.

~/olada/nuxt-starter-ebey3puz main 5m 37s
❯ npx nuxi info
Working directory: /home/olada/nuxt-starter-ebey3puz                                                                                                                  nuxi  00:02:09
Nuxt project info:                                                                                                                                                    nuxi  00:02:09

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.16.1
- CLI Version:      3.23.1
- Nitro Version:    2.11.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, pages, modules
- Runtime Modules:  @nuxt/test-utils/module@3.17.2
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com


~/olada/nuxt-starter-ebey3puz main 2s
❯ pnpx nuxi info
Packages: +1
+
Progress: resolved 1, reused 0, downloaded 1, added 1, done
Working directory: /home/olada/nuxt-starter-ebey3puz                                                                                                                  nuxi  00:02:27
Nuxt project info:                                                                                                                                                    nuxi  00:02:27

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.16.1
- CLI Version:      3.23.1
- Nitro Version:    2.11.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, pages, modules
- Runtime Modules:  @nuxt/test-utils/module@3.17.2
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com
```

### PR DESCRIPTION
**Pull request by wattanx**
### 🔗 Linked issue
Fixes: https://github.com/nuxt/test-utils/issues/1203

### 📚 Description
`@nuxt/test-utils` unignored `*.spec.*` / `*.test.*` files so test files could be transformed by Nuxt, but this also caused files under `plugins/` to be treated as Nuxt plugins. As a result, `plugins/*.spec.ts` could be evaluated through Nuxt's plugin pipeline before Vitest collected the suite, so the tests were not collected correctly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
❤️

File: src/module/mock.ts [hunk 1]
```diff
@@ -5,6 +5,10 @@ import { createMockPlugin } from './plugins/mock'
 import type { MockPluginContext } from './plugins/mock'
 import { loadKit } from '../utils'
 
+function isTestPluginFile(src: string) {
+  return src.includes('/plugins/') && (src.includes('.spec.') || src.includes('.test.'))
```
Comment (danielroe) [inline src/module/mock.ts]: I think we can probably drop the first part of the line as we already know the `src` is a plugin.

```suggestion
  return (src.includes('.spec.') || src.includes('.test.'))
```
