### PR TITLE
fix(e2e): detect nuxt config files in `.config` folder

### LINKED ISSUE #893: e2e tests fail with Nuxt 4 config settings
### Environment

Reproduction: https://stackblitz.com/edit/github-gu1sj1?file=tests%2Fbasic.e2e.test.ts

I can't seem to utilize the alternative nuxt.config location with @nuxt/test-utils. If I have my nuxt.config as `./.config/nuxt.ts`, e2e tests will always fail with  `Error: Invalid nuxt app. (Please explicitly set 'options.rootDir' pointing to a valid nuxt app)`.

This is my test:
```js
// ./tests/basic.e2e.test.ts
import { $fetch, setup } from '@nuxt/test-utils/e2e';
import { describe, expect, it } from 'vitest';

describe('basic', async () => {
  await setup({
    rootDir: './app',
    configFile: '/.config/nuxt.ts',
  });

  it('contains Welcome to Nuxt! string', async () => {
    const html = await $fetch('/');
    expect(html).toContain('Welcome to Nuxt!');
  });
});
```
and my nuxt.config:
```js
// ./.config/nuxt.ts
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  future: {
    compatibilityVersion: 4,
  },
  modules: ['@nuxt/test-utils/module'],
});
```
If I move and rename nuxt.config back to the root, it works.

I'm not sure if this is a limitation or expectation of test-utils of the config file name/location that isn't being honored by the `configFile` setting, or what.

### Reproduction

https://stackblitz.com/edit/github-gu1sj1?file=tests%2Fbasic.e2e.test.ts

### Describe the bug

Using alternative nuxt.config name/location causes e2e tests to fail.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Yizack**
### 🔗 Linked issue

Resolves #893

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Some people are using the `.config` folder alternative for projects with many configuration files, and since `c12` from `unjs` and `nuxt` itself support `.config` folder would be nice to be able run tests using this alternative :)

Added support for detecting Nuxt apps that use config files inside the `.config` folder. I hardcoded the possible resolvable configs following the same pattern as the existing for default config files. No need to set `coonfigFile` option

Also added a `dot-config` test fixture in `examples/module/test/fixtures`

### CODE REVIEW

File: src/e2e/nuxt.ts [hunk 1]
```diff
@@ -14,6 +14,10 @@ const isNuxtApp = (dir: string) => {
     || existsSync(resolve(dir, 'nuxt.config.mjs'))
     || existsSync(resolve(dir, 'nuxt.config.cjs'))
     || existsSync(resolve(dir, 'nuxt.config.ts'))
+    || existsSync(resolve(dir, '.config', 'nuxt.js'))
+    || existsSync(resolve(dir, '.config', 'nuxt.mjs'))
```
Comment (danielroe) [inline src/e2e/nuxt.ts:18]: thank you!

maybe ultimately we might try to get a `resolveConfigPath` into `c12` so we have one location for configuration resolution (cc: @pi0)
